dist: xenial
language: python
python:
    - '3.7-dev'
    - '3.8-dev'
install:
    - pip install poetry
    - poetry install
script:
    - poetry run pytest -c tests/pytest.ini
after_success:
    - poetry run codecov
