[tool.poetry]
name = "genlib"
version = "0.1.0"
description = ""
authors = ["Alex J. Champandard <alexjc@nucl.ai>"]
license = "AGPL-3.0"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
